#!/usr/bin/env python
#
# A tool to create publication list as an html or tex file, based on a bib file (YAML).
#
# Developed for Python 2.7
#
# Gokberk Cinbis, 2017

# A small note regarding pip on MAC: usually /usr/bin/python and /usr/local/bin/python 
# are independent. Make sure you install required packages using the right pip.

# TODO
# - sort option

from jinja2 import Environment, FileSystemLoader
import argparse
import yaml     # pip install pyyaml
import os
import sys

template_search_path = [os.getcwd(),os.path.dirname(os.path.abspath(__file__))]

class Bib2Doc:
    """
    Generic conversion class, shared across all publication list generators (html, tex, etc).
    This class shall be kept independent from the "args" structure used in specific convertion scripts.
    
    USAGE
    - Create the file
    - Call sort_pubs() to sort the publications (optional)
    - Call process() to create & generate the output file
    """

    def __init__(self,bibfile):
        self.bibfile = bibfile
        self.bib = self.load_bib()

    def count_types(self,types):
        """ Count number of papers with type in types """
        count = 0
        for p in self.bib:
            try:
                if p['type'] in types:
                    count = count + 1
            except Exception:
                print(p)
            
        return count

    def count_preprint(self):
        """ Count number of papers with type = under_review or working_paper """
        return self.count_types(['under_review','working_paper'])

    def load_bib(self):
        """
        Read the publications database
        """
        bib = []
        with open(self.bibfile, "r") as f:
            collections = yaml.load_all(f) 
            for records in collections: # there is normally a single "records" in "collections"
                for paper in records:
                    bib.append(paper)
        return bib

    @staticmethod
    def fix_html_ampersand(paper):
        """
        Replace & with &amp; in all string-valued fields of paper except the following: {pdf,img}
        """
        for key in paper:
            if key in {'pdf','img'}:
                continue # do not alter these fields as they contain link/path.
            if type(paper[key])==str:
                paper[key] = paper[key].replace('&','&amp;') 
        return paper

    @staticmethod
    def get_pdf_href(paper):
        """ Utility function that returns paper.pdf or '#' """
        return paper['pdf'] if Bib2Doc.isdef(paper,'pdf') else '#' 

    @staticmethod
    def get_venue(paper):
        """ Return journal/conference name """
        if Bib2Doc.isdef(paper,'type') and (paper['type'] == 'journal'):
            return paper['journal']
        else:
            return paper['booktitle']

    _month2name = {1: 'January', 2: 'February', 3: 'March', 4: 'April', 5: 'May', 6: 'June', 7: 'July', 
            8: 'August', 9: 'September', 10: 'October', 11: 'November', 12: 'December'}

    @classmethod
    def get_month_name(cls,paper):
        """
        Utility function to get month name for a paper.
        Return "" if paper.month is undefined or unrecognized
        """
        try:
            return cls._month2name[paper['month']]
        except Exception as e:
            return ""

    @staticmethod
    def isdef(paper,field):
        """ Return True iff paper[field] is defined and not empty """
        return True if ((field in paper) and (paper[field])) else False

    @staticmethod
    def getstrfield(paper,field):
        """ Return paper[field] (if defined) or '' """
        try:
            return paper[field]
        except Exception:
            return ""

    @staticmethod
    def get_vol_num_pp_loc_mon_year(p):
        """ Return a string according to the following template and the available information: 'volume (number), pp. pages, location, month year' """
        out = ''
        # Don't force "journal" type -- if Bib2Doc.getstrfield(p,'type')=='journal' --
        if Bib2Doc.isdef(p,'volume'):
            if Bib2Doc.isdef(p,'number'):
                out += str(p['volume']) + '(' + str(p['number']) + '),'
            else:
                out += str(p['volume']) + ","
        if Bib2Doc.isdef(p,'pages'):
            out += 'pp. ' + str(p['pages']) + ', '
        if Bib2Doc.isdef(p,'location'):
            out += p['location'] + ', '
        out += Bib2Doc.get_month_name(p) + ' ' # possibly ""
        if Bib2Doc.isdef(p,'year'):
            out += str(p['year'])
        return out

    @staticmethod
    def field2htmllink(paper,field,text=None,target="_blank",css_class=''):
        """ 
        Return HTML link with href=paper.field, if paper[field] is defined, and '' otherwise. 
        Text is field by default.
        """
        if not (css_class == ''):
            css_class = ' class="' + css_class + '"'
        return ("<a href=" + paper[field] + ' target="' + target + css_class + '">' + (text or field) + '</a>') if Bib2Doc.isdef(paper,field) else ""

def getargs():
    parser = argparse.ArgumentParser(description='''
        Create a publication list document, based on a jinja2 template and a YAML bibliograph file.
        ''')
    parser.add_argument('bibfile',help='Path of the YAML bib file.')
    parser.add_argument('template',help='Path of the jinja2 based HTML template.')
    parser.add_argument('outputfile',help='Path of the output file.')
    args = parser.parse_args()
    
    return args

if __name__ == "__main__":
    args = getargs()
    bib2doc = Bib2Doc(args.bibfile)
    env = Environment(loader=FileSystemLoader(template_search_path),trim_blocks=True)
    template = env.get_template(args.template)
    template.stream(bib2doc=bib2doc).dump(args.outputfile)

