#!/bin/bash
set -e

# to concatenate pdf files: catpdf input1 input2 .. inputN output
# usage: catpdf *pdf output.pdf

#function catpdf() {
    #local args=($*) -- does not handle quotes.
    #local narg=${#args[@]}
    #local out=${args[$narg-1]}
    narg=$#
    out=${!narg}

    # avoid overwriting by mistake
    if [ -f "$out" ]
    then
        echo "Output: '$out' already exists. First delete existing output file."
        return 1
    fi

    cmd="gs -q -sPAPERSIZE=letter -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=\"$out\"" 

    for (( i = 1 ; i < $narg; i++ ))
    do
        cmd="$cmd \"${!i}\"" # add \"...\" to support filenames with spaces
    done    
    
    echo $cmd
    eval $cmd # use eval to parse quotes properly (see more here: https://stackoverflow.com/questions/411495/build-argument-lists-containing-whitespace)
#}

#catpdf "$@"

