#!/bin/bash
set -e

if [ $# -ne 2 ]; then
    echo "USAGE: git-difftool-prevn <dir1> <dir2>"
    echo "Diffs two directories, based on file-names only"
    exit 1 
fi
args=("$@")  # preserves ".." groups
narg=${#args[@]}
git difftool "HEAD@{$1}" ${args[@]:1:$narg}



