#!/bin/bash
# Author: Gokberk Cinbis, 2021
set -e

function __increment_argi__() # just increment argi variable
{
    argi=$((argi+1))
}


function __decrement_argi__() # just decrement argi variable
{
    argi=$((argi-1)) 
}


function __print_help__ () 
{
    echo "findgrep [-i] [-n <ptn>] [-e <ext>] [--debug] <regexp>"
    echo "Search all files recursively, list files and matches for those matching with <regexp>"
    echo ""
    echo "ARGUMENTS"
    echo "-i          Optional ignore case option."
    echo "-n <ptn>    Optional name argument, restrict search to file names matching <ptn>"
    echo "-e <ext>    Optional extension argument, restrict search to *.<ext>." 
    echo "--list-only List matching files only, not their content."
    echo "--debug     Don't execute the command, just print the final find command."
    echo "<regexp>    Regular expression."
    exit 1
}

function __main__()
{
    local narg=$#
    local regexp="${!narg}" # last argument

    if [ $narg -lt 1 ]
    then
        __print_help__
    fi

    findargs=()
    grepargs=()
    debug=0

    argi=0 # argument reading index
    for (( argi=1; argi<=$((narg-1)); argi++ )); do
        if [ "${!argi}" == '-i' ]; then  
            grepargs+=('--ignore-case')
        elif [ "${!argi}" == '--debug' ]; then  
            debug=1
        elif [[ "${!argi}" == '-n' ]]; then  
            __increment_argi__
            if [ $argi -eq $narg ]; then
                __print_help__ # we'd read <regexp> as <ext> incorrectly
            fi
            # doesnt work: findargs+=('-name' "\"*.${!argi}\"")
            findargs+=('-name' "${!argi}")

        elif [[ "${!argi}" == '-e' ]]; then  
            __increment_argi__
            if [ $argi -eq $narg ]; then
                __print_help__ # we'd read <regexp> as <ext> incorrectly
            fi
            # doesnt work: findargs+=('-name' "\"*.${!argi}\"")
            findargs+=('-name' "*.${!argi}")
        elif [[ "${!argi}" == '--list-only' ]]; then  
            __increment_argi__
            grepargs+=("--files-with-matches")
        else
            command echo "Unrecognized argument: {!argi}"
            __print_help__
        fi
    done

    # -H filename
    # -n line number
    if [ $debug -eq 1 ]; then
        echo command find -L . "${findargs[@]}" -type f -exec grep -H -n --color "${grepargs[@]}" "$regexp" {} \;
    else
        command find -L . "${findargs[@]}" -type f -exec grep -H -n --color "${grepargs[@]}" "$regexp" {} \;
    fi
    # Example simple case: command find . -type f -L -name "*.$1" -exec grep -H --color "$2" {} \;
}

# ok with multiple quoted arguments
__main__ "$@"
exit 0

