#!/bin/bash
set -e

if [ $# -ne 1 ]; then
    echo "git-remember-passwords <sec>"
    echo ""
    echo "  Turns on git credential helper (ie. to avoid asking password everytime in overleaf, etc.) and "
    echo "  sets the limit to <sec> seconds."
    echo ""
    echo "  Example (remember for 1 hour): git-remember-passwords 3600"
    echo "  Example (remember for 1 day): git-remember-passwords 86400"
    echo ""
    echo "Reference: https://help.github.com/en/articles/caching-your-github-password-in-git"
    exit 1 
fi

# "Set git to use the credential memory cache"
git config --global credential.helper cache

# "Set the cache to timeout after 1 hour (setting is in seconds)"
echo git config --global credential.helper "cache --timeout=$1"
git config --global credential.helper "cache --timeout=$1"
echo done

