#!/bin/bash
set -e

if [ $# -le 0 ]; then
    echo "USAGE: git-difftool-prevn <N> [optional-filename(s)]"
    echo "Diffs to <N>th previous commit."
    exit 1 
fi
args=("$@")  # preserves ".." groups
narg=${#args[@]}
# old: git difftool "HEAD@{$1}" ${args[@]:1:$narg}
echo git difftool HEAD~"$1" ${args[@]:1:$narg}
git difftool HEAD~"$1" ${args[@]:1:$narg}



