#!/bin/bash
# Author: Gokberk Cinbis, 2017
set -e

if [ "$#" -eq 1 ]; then
    file="$1"
else
    echo 'git_writehash <file>'
    echo ''   
    echo 'Write git hash into a file. Exists if file already exists.'
    echo ''   
    echo 'SUGGESTED USE'   
    echo 'Call git_uniqueid to generate a log directory in the beginning of an experiment script'   
    echo 'Call git_writehash to write the current hash into a file into the log directory'
    echo 'Call git_checkhash at test time to make sure that the right revision is being used at evaluation time (if necessary)'
    echo ''   
    echo 'PACKAGE'
    echo 'git_uniqueid    Generate a unique log file/directory name for running an experiment'
    echo 'git_writehash   Write git hash into a file'
    echo 'git_checkhash   Check whether the current git hash to make sure the right code-base is being used for evaluating a pre-trained model'
    exit 3
fi

if [ -f $file ]
then
    echo "Output: $file already exists. First delete existing output file."
    exit 1
fi

command git rev-list --full-history --all | head -1 > $file

