#!/bin/bash
#
# Author: Gokberk Cinbis, 2018
#
# Useful references: 
# * https://www.omgubuntu.co.uk/2017/07/adjust-color-temperature-gnome-night-light

set -e

function print_settings_and_exit {
    for x in "active" "night-light-enabled" "night-light-schedule-automatic" "night-light-schedule-from" "night-light-schedule-to" "night-light-temperature"; do
        echo "$x:" `gsettings get org.gnome.settings-daemon.plugins.color $x`
    done
    exit 0
}

function get_cur_temp_setting {
    local x=$(gsettings get org.gnome.settings-daemon.plugins.color night-light-temperature)
    local x=${x/uint32 /}
    echo $x
}

function increment_by {
    local old=$(get_cur_temp_setting)
    local new1=$(expr $old + $1)
    gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature "$new1"
    local new2=$(get_cur_temp_setting)
    echo "Changed the color temperature from $old K to $new2 K"
}

function print_help_and_exit() {
    echo 'Utility to alter screen color temperature settings easily in GNOME.'
    echo ''
    echo 'USAGE'
    echo 'gnome-color-temperature info'
    echo '  Print current settings.'   
    echo ''
    echo 'gnome-color-temperature +'
    echo '  Increase color temperature by 250 K. (cooler)'   
    echo ''
    echo 'gnome-color-temperature -'
    echo '  Decrease color temperature by 250 K. (warmer)'   
    echo ''
    echo 'gnome-color-temperature custom <value>'
    echo '  Set color temperature to <value>.'   
    echo ''
    echo 'gnome-color-temperature custom <value>'
    echo '  Set color temperature to <value>.'   
    echo ''
    echo 'gnome-color-temperature <preset>'
    echo '  Set color temperature to a predefined value, using the following table.'   
    echo '     cool: 6500'
    echo '     balanced-cooler: 6000'
    echo '     balanced-cool: 5750'
    echo '     balanced: 5500'
    echo '     balanced-warm: 5000'
    echo '     balanced-warmer: 4500'
    echo '     warm: 4000'
    echo ''
    echo 'gnome-color-temperature all-day'
    echo '  Enable the tool and set all day active.'   
    echo ''
    echo 'gnome-color-temperature location-based'
    echo '  Enable the tool and its location-based scheduling option.'
    echo ''
    echo 'gnome-color-temperature disable'
    echo '  Disable.'   
    echo ''
    echo 'gnome-color-temperature editor'
    echo '  Open settings in dconf-editor.'   
    exit 1
}

if [ "$#" -eq 0 ]; then
    print_help_and_exit
fi

opt1="$1"

if [ "$opt1" == "info" ]; then
    print_settings_and_exit
fi

if [ "$opt1" == "editor" ]; then
    dconf-editor org.gnome.settings-daemon.plugins.color
    exit 0
fi

if [ "$opt1" == "+" ]; then
    increment_by 250
    exit 0
fi

if [ "$opt1" == "-" ]; then
    increment_by -250
    exit 0
fi

if [ "$opt1" == "custom" ]; then
    gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature "$2"
    exit 0
fi

if [ "$opt1" == "warm" ]; then
    gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature 4000
    exit 0
fi

if [ "$opt1" == "balanced-warmer" ]; then
    gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature 4500
    exit 0
fi

if [ "$opt1" == "balanced-warm" ]; then
    gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature 5000
    exit 0
fi

if [ "$opt1" == "balanced" ]; then
    gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature 5500
    exit 0
fi

if [ "$opt1" == "balanced-cooler" ]; then
    gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature 6000
    exit 0
fi

if [ "$opt1" == "balanced-cool" ]; then
    gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature 5750
    exit 0
fi

if [ "$opt1" == "cool" ]; then
    gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature 6500
    exit 0
fi

if [ "$opt1" == "all-day" ]; then
    gsettings set org.gnome.settings-daemon.plugins.color active true
    gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
    gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-automatic false
    gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-from 0
    gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-to 23.59
    exit 0
fi

if [ "$opt1" == "disable" ]; then
    gsettings set org.gnome.settings-daemon.plugins.color active true
    gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled false
    exit 0
fi

if [ "$opt1" == "location-based" ]; then
    gsettings set org.gnome.settings-daemon.plugins.color active true
    gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
    gsettings set org.gnome.settings-daemon.plugins.color night-light-schedule-automatic true
    exit 0
fi

# haven't exited yet, print help and exit
print_help_and_exit

