#!/bin/bash
set -e

if [ $# -le 1 ]; then
    echo "grep-with-char-context <numchars-before/after> <pattern> <filename1> <filename2> <...>"
    echo "Print results with character context for a specified number of characters."
    exit 1
fi

narg=$#
out=${!narg}

cmd="grep -no '.\{0,$1\}$2.\{0,$1\}'"
for (( i = 3 ; i <= $narg; i++ ))
do
    cmd="$cmd \"${!i}\"" # add \"...\" to support filenames with spaces
done    

#echo $cmd
eval $cmd # use eval to parse quotes properly (see more here: https://stackoverflow.com/questions/411495/build-argument-lists-containing-whitespace)

