#!/bin/bash

if [ $# -ne 3 ]
then
    echo "Usage: mycomparepdf <pdf1> <pdf2> <numberOfPages>"
    echo "Output files are named __delta__<page>.pdf"
    echo "Requires ImageMagick's compare tool"
    exit 1 
fi

end=$(expr $3 - 1)
for i in `seq 0 $end`;
do
    echo compare  "$1"[$i] "$2"[$i] -compose src __delta__$i.pdf
    compare  "$1"[$i] "$2"[$i] -compose src __delta__$i.pdf
done

