#!/bin/bash 
#
# Gokberk Cinbis, May 2025

function __pdfannots__()
{
    pdfannots --no-condense --no-page-labels "$1"
}

function __main__()
{
    local narg=$#
    local regexp="${!narg}" # last argument

    if [ $narg -lt 1 ]
    then
        echo "USAGE: pdfannots-clipboard <filename>"
        echo ""
        echo "A wrapper on pdfannots, a cleaned-up version of pdfannots is saved into the clipboard."
        echo ""
        echo "pdfannots installation:"
        echo "   - MacOS: pip3 install pdfannots"
        echo "   - Linux: sudo apt install pipx"
        echo "            pipx install pdfannots"
        exit 1
    fi

    # https://stackoverflow.com/questions/3466166/how-to-check-if-running-in-cygwin-mac-or-linux
    local unameOut="$(\uname -s)"
    case "${unameOut}" in
        Linux*)     machine=Linux;;
        Darwin*)    machine=Mac;;
        CYGWIN*)    machine=Cygwin;;
        MINGW*)     machine=MinGw;;
        *)          machine="UNKNOWN:${unameOut}"
    esac

    # Replacing output with * - causes two-level list. * | is much better.
    local __sed_mac='s/^ \* Page.*/\* |/'
    local __sed_lnx=__sed_mac

    if [[ $machine == "Mac" ]]; then
        __pdfannots__ "$1" | sed "$__sed_mac" | pbcopy
    elif [[ $machine == "Linux" ]]; then
        __pdfannots__ "$1" | sed "$__sed_lnx" | xsel -ib
    else
        echo "Unsupported OS."
        exit 2
    fi

    echo "Markdown output has been saved into the clipboard."

}

# ok with multiple quoted arguments
__main__ "$@"
exit 0

